# Generated by Django 5.0.2 on 2024-03-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
            ],
        ),
    ]
